export enum CaptableKeys {
    INVESTORS_DATA_ERROR = "captable.INVESTORS_DATA_ERROR",
    EMPLOYEES_DATA_ERROR = "captable.EMPLOYEES_DATA_ERROR",
    ESOP_DATA_ERROR = "captable.ESOP_DATA_ERROR",
    TOTAL_CALCULATIONS_ERROR = "captable.TOTAL_CALCULATIONS_ERROR",
    CAPTABLE_DATA_ERROR = "captable.CAPTABLE_DATA_ERROR",
    EXISTING_SHARES_ERROR = "captable.EXISTING_SHARES_ERROR",
}
