export enum EmployeeKeys {
    NOT_FOUND = "employee.NOT_FOUND",
    CREATION_ERROR = "employee.CREATION_ERROR",
    UPDATE_ERROR = "employee.UPDATE_ERROR",
    UPDATED_SUCCESSFULLY = "employee.UPDATED_SUCCESSFULLY",
    CANT_DELETE = "employee.CANT_DELETE",
    DELETED_SUCCESSFULLY = "employee.DELETED_SUCCESSFULLY",
    COMPANY_ACCESS_DENIED = "employee.COMPANY_ACCESS_DENIED",
    EMAIL_EXISTS = "employee.EMAIL_EXISTS",
    SUBORDINATES_ERROR = "employee.SUBORDINATES_ERROR",
    EMPLOYEES_VESTING_ERROR = "employee.EMPLOYEES_VESTING_ERROR",
    UPDATE_EMPLOYEES_VESTING_ERROR = "employee.UPDATE_EMPLOYEES_VESTING_ERROR",
    CANT_DELETE_ORGANIZATION_HEAD = "employee.CANT_DELETE_ORGANIZATION_HEAD",
}
